// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cMBKRall
NumericVector cMBKRall(NumericVector Ti, NumericVector censor, NumericMatrix X, NumericVector weight_C);
RcppExport SEXP _GLASMcensor_cMBKRall(SEXP TiSEXP, SEXP censorSEXP, SEXP XSEXP, SEXP weight_CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Ti(TiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censor(censorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight_C(weight_CSEXP);
    rcpp_result_gen = Rcpp::wrap(cMBKRall(Ti, censor, X, weight_C));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GLASMcensor_cMBKRall", (DL_FUNC) &_GLASMcensor_cMBKRall, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GLASMcensor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
