# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The proposed marginal screening method based on the BKR independence test
#' @name cMBKRall
#' @param Ti is the vector of the ordered censored Time (ascent)
#' @param censor is the censor indicator for the Ti. 1 means no censor and 0 means censoring.
#' @param X is the complete covariates for the samples.
#' @param weight_C the inverse weight in the survival analysis. it is the output of the function KMestimate_CTime.
#' @export
#' @return the cBKRmeasure
NULL

cMBKRall <- function(Ti, censor, X, weight_C) {
    .Call(`_GLASMcensor_cMBKRall`, Ti, censor, X, weight_C)
}

